README.md

Corrected readme spelling mistake

---

README.md

docs: fix contributions link

---

.gitignore
cmd/eks-node-viewer/flag.go
cmd/eks-node-viewer/main.go
pkg/client/client.go

https://github.com/awslabs/eks-node-viewer/issues/33
Adding option to read default value from config file. This default value can be overridden by flag.

add option for config file

---

README.md
cmd/eks-node-viewer/flag.go
cmd/eks-node-viewer/main.go

- rename config file to match binary name
- rename node-selector flag to match the others
- document config file

fix: rename the config file and node-selector flag and update docs

---

cmd/eks-node-viewer/main.go

fix: ignore terminal pods

---

cmd/eks-node-viewer/main.go
pkg/model/node.go
pkg/model/node_test.go
pkg/model/uimodel.go

Until we fix fargate node support, at least display them as blank.

fix: don't assume nodes are either spot or on-demand

---

README.md
cmd/eks-node-viewer/main.go
pkg/model/cluster.go

Fixes: #51, #38 and #36
Fix the check for terminal pods.

Enhancements

---

pkg/model/uimodel.go

*Issue #58 
Fixes: #58 
Lowers node time precision to Miliseconds.

feat: Lower node time precision

---

README.md
pkg/model/uimodel.go

*Issue #, if available:* n/a
* Print `-` as a placeholder when some info is not relevant

feat: Add node info placeholders

---

cmd/eks-node-viewer/main.go
pkg/pricing/pricing.go

Fixes  #63
Treat spot price as unknown if we don't know it instead of falling back to the OD price.

Fix spot price

---

pkg/model/cluster.go

Fix concurrency bug

---

.github/workflows/go.yml
ATTRIBUTION.md
Makefile
README.md
cmd/eks-node-viewer/.gitignore
cmd/eks-node-viewer/flag.go
cmd/eks-node-viewer/main.go
go.mod
go.sum
hack/attribution.tmpl
hack/gen_licenses.sh

add open source attribution

---

.github/dependabot.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml
.gitignore
.golangci.yaml
.goreleaser.yaml
Makefile
README.md
cmd/eks-node-viewer/flag.go
cmd/eks-node-viewer/main.go

*Issue #13 
Fixes: #13 
* Adds support for binary version
* Add automatic release pipeline via GoReleaser by pushing a new tag
* New Makefile targets for local execution and build
* Update README to reflect the changes
* Removal of empty spaces and formatting

feat: Add version support and release pipeline

---

.github/workflows/release.yaml

use stable go for releases

---

cmd/eks-node-viewer/.gitignore
cmd/eks-node-viewer/ATTRIBUTION.md

check in the attribution file so go install will work

---

pkg/model/uimodel.go

*Issue #, if available:* n/a
Improves status output and adds missing `$` for hourly price estimate ;)

feat: Improve status outputs

---

cmd/eks-node-viewer/main.go
pkg/model/node.go
pkg/model/node_test.go
pkg/model/pod.go
pkg/model/pod_test.go
pkg/model/uimodel.go
pkg/pricing/pricing.go

Fargate Pricing - #35 
Show another digit of precision for prices - #87
Support fargate nodes.

support fetching fargate prices and reporting fargate nodes

---

README.md
pkg/model/node.go
pkg/model/uimodel.go

#90
Supports display of custom computed labels.

Support computed labels

---

README.md

#17 
Document installation via homebrew.

document installing with homebrew

---

ATTRIBUTION.md
cmd/eks-node-viewer/ATTRIBUTION.md
go.mod
go.sum

chore: update attribution

---

README.md

Small typo in the Karpenter name
Changed Karenter to Karpenter in the README

docs(README.md) Karpenter name typo

---

ATTRIBUTION.md
cmd/eks-node-viewer/ATTRIBUTION.md
pkg/model/uimodel.go

Show the pending pod count, even if no nodes are present in the cluster.

show pending pod count even if no nodes are present

---

pkg/model/uimodel.go

check bounds from paginator

---

pkg/model/node.go

Short-circuits the pricing lookup in favor of a hard coded label value `instance-price`. Tested manually. 

feat: add price override label for nodes

---

.goreleaser.yaml
hack/gen_licenses.sh

Updates goreleaser config so it works again.

fix the goreleaser config

---

ATTRIBUTION.md
cmd/eks-node-viewer/ATTRIBUTION.md
pkg/aws/zz_generated_aws.pricing.go
pkg/aws/zz_generated_aws_us_gov.pricing.go

update generated code
